---

- name: Create a virtual machine and configure as a build environment in Azure
  hosts: localhost

  vars:
    ansible_python_interpreter: /opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
    resourceGroupName: my-base-rg
    location: australiaeast
    network:
      name: vnet
      cidr: 10.0.0.0/22
      subnet:
        name: vm-subnet
        cidr: 10.0.0.0/24
      nsg:
        name: vm-nsg
    vm:
      ssh_key_path: '~/.ssh/id_rsa.pub'
      ssh_priv_key_path: '/.ssh/id_rsa'
      size: Standard_B1s
      name: build-vm
      public_ip:
        enable: true
        name: build-vm-pip
      nic:
        name: build-vm-nic
      image:
        offer: 0001-com-ubuntu-server-jammy
        sku: 22_04-lts
  
  tasks:

    - name: Get the current user name
      ansible.builtin.command: whoami
      register: userdetails

    - name: Get the current users internet address
      ansible.builtin.uri:
        url: "http://checkip.amazonaws.com/"
        return_content: true
      register: my_ip
    
    - name: Confirm that the SSH public key exists
      ansible.builtin.stat:
        path: "{{ vm.ssh_key_path }}"
      register: ssh_key_file

   - name: Confirm that the SSH private exists
      ansible.builtin.stat:
        path: "{{ vm.ssh_priv_key_path }}"
      register: ssh_priv_key_file

    - name: Fail if the ssh_key_file does not exist
      ansible.builtin.fail:
        msg: "ERORR: Either public or private key not found."
      when: not ssh_key_file.stat.exists or
            not ssh_priv_key_file.stat.exists
    
    - name: Create a new Azure resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resourceGroupName }}"
        location: "{{ location }}"
      register: rg
    
    - name: Create a new Azure virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resourceGroupName }}"
        name: "{{ network.name }}"
        address_prefixes: 
          - "{{ network.cidr }}"
      register: vnet

    - name: Create a new Network Security Group for the subnet
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resourceGroupName }}"
        name: "{{ network.nsg.name }}"
        purge_rules: true
        rules:
          - name: AllowSSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 100
            direction: Inbound
            source: {{ my_ip.stdout }}
      register: nsg
       
    - name: Create a new Azure subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resourceGroupName }}"
        name: "{{ network.subnet.name }}"
        address_prefix_cidr: "{{ network.subnet.cidr }}"
        virtual_network_name: "{{ vnet.state.name }}"
      register: subnet

    - name: Create an Azure network interface
      azure.azcollection.azure_rm_networkinterface:
        name: "{{ vm.nic.name }}"      
        resource_group: "{{ resourceGroupName }}"
        virtual_network: "{{ vnet.state.name }}"
        subnet_name: "{{ subnet.state.name }}"
        security_group: "{{ nsg.state.name }}"
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: "{{ vm.public_ip.name }}"
            primary: true
      register: nic

    - name: Get the information on the created public IP
      azure.azcollection.azure_rm_publicipaddress_info:
        resource_group: "{{ resourceGroupName }}"
        name: "{{ vm.public_ip.name }}"
      register: publicIP    

    - name: Create a new Ubuntu virtual machine with SSH key on the created subnet
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resourceGroupName }}"
        name: "{{ vm.name }}"
        vm_size: Standard_B1s
        admin_username: "{{ userdetails.stdout }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/{{ userdetails.stdout }}/.ssh/authorized_keys
            key_data: "{{lookup('ansible.builtin.file', '{{ vm.ssh_key_path }}') }}"
        security_profile:
          encryption_at_host: true
        network_interfaces: "{{ nic.state.name }}"
        image:
          offer: "{{ vm.image.offer }}"
          publisher: Canonical
          sku: "{{ vm.image.sku }}"
          version: latest
      register: buildvm

    - name: Set the IP address
      set_fact:
        buildvm_IP: "{{ publicIP.publicipaddresses[0].ip_address  }}"

    - name: Show IP address
      debug:
        msg: "Public IP address is {{ buildvm_IP }}"

    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

    - name: Register buildvm as host
      ansible.builtin.add_host:
        hostname: "{{ buildvm_IP  }}"
        key: "{{ vm.ssh_priv_key_file }}"
        group: created_hosts

    - name: Add new host to list of known hosts
      ansible.builtin.shell: |
        set timeout 300
        ssh -o StrictHostKeyChecking=no -i {{ vm.ssh_priv_key_file }} {{ userdetails.stdout }}@{{ buildvm_IP  }} 'echo $USERID'

    # - name: SSH to the virtual machine and perform an apt update
    #   ansible.builtin.shell: |
    #     set timeout 300

    #     ssh -i {{ vm.ssh_priv_key_path }} {{ userdetails.stdout }}@{{ buildvm_IP }} \
    #       "sudo apt update && sudo apt -y dist-upgrade"

    #     exit 0
    #   args:
    #     executable: "{{default.shell}}"
    #   delegate_to: localhost

    # - name: Install az cli on virtual machine
    #   ansible.builtin.shell: |
    #     set timeout 300
    #     ssh -i {{ vm.ssh_priv_key_path }} {{ userdetails.stdout }}@{{ buildvm_IP }} \
    #       "curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"

    #     exit 0
    #   args:
    #     executable: "{{default.shell}}"
       
- name: Setup build virtual machine
  hosts: created_hosts
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'
    default:
      shell: /bin/bash
      temp_dir: '/tmp'
      bin_dir: '/usr/local/bin'
    packages:
      podman: true
      az: true
      terraform: true
      oc: true
      jq: true
      helm: true

  tasks:

    - name: Update packages on server
      apt:
        upgrade: dist

    # - name: Install az cli on virtual machine
    #   raw: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install az cli on host
      ansible.builtin.shell: |
        set timeout 300
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        exit 0
      when: packages.az
    
    - name: Install jq package on host
      apt:
        state: present
        name:
          - jq
        update_cache: true
      when: packages.jq

    - name: Install podman packages on host
      apt:
        state: present
        name:
          - jq
          - podman
        update_cache: true
      when: packages.podman

    - name: Install helm package on host
      apt:
        state: present
        name:
          - helm
        update_cache: true
      when: packages.helm

    - name: Install Red Hat oc cli on host
      ansible.builtin.shell: |
        set timeout 300
        TMP_DIR="{{ default.temp_dir }}""
        BIN_DIR="{{ default.bin_dir }}""
        ARCH=$(uname -m)
        OC_FILETYPE="linux"
        KUBECTL_FILETYPE="linux"
        OC_URL="https://mirror.openshift.com/pub/openshift-v4/${ARCH}/clients/ocp/latest/openshift-client-${OC_FILETYPE}.tar.gz"

        curl -Lo $TMP_DIR/openshift-client.tgz $OC_URL
        tar xzf ${TMP_DIR}/openshift-client.tgz -C ${TMP_DIR} oc
        mv ${TMP_DIR}/oc ${BIN_DIR}/oc
        rm ${TMP_DIR}/openshift-client.tgz
        exit 0
      when: packages.oc

    - name: Install hashicorp terraform on host
      ansible.builtin.shell: |
        set timeout 300
        apt update && apt install -y gnupg software-properties-common
        wget -O- https://apt.releases.hashicorp.com/gpg | \
          gpg --dearmor | \
          tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          tee /etc/apt/sources.list.d/hashicorp.list
        apt update
        apt install -y terraform
        exit 0
      when: packages.terraform

    
    